### ISSUE TITLE
julia> Pkg.add("IJulia")におけるエラー

### ISSUE THREAD

**Issue by 13tsuyoshi** [OyamaZemi/Settingup#1]
ターミナルで以下のエラーが出ていて、対処に困っています。

julia> Pkg.add("IJulia")
INFO: Initializing package repository /home/9720514486/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: ArgumentError: '/home/9720514486/.julia/v0.4/REQUIRE' exists. `remove_destination=true` is required to remove '/home/9720514486/.julia/v0.4/REQUIRE' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in init at pkg/dir.jl:63
 in cd at pkg/dir.jl:28
 in add at pkg.jl:23

**Comment by 13tsuyoshi** [comment]
Pkg.status()
INFO: Initializing package repository /home/9720514486/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: ArgumentError: '/home/9720514486/.julia/v0.4/REQUIRE' exists. `remove_destination=true` is required to remove '/home/9720514486/.julia/v0.4/REQUIRE' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in init at pkg/dir.jl:63
 in cd at pkg/dir.jl:28
 in status at pkg.jl:32 (repeats 2 times)

**Comment by 13tsuyoshi** [comment]
上のようになりました

**Comment by 13tsuyoshi** [comment]
Pkg.status()
INFO: Initializing package repository /home/9720514486/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: ArgumentError: '/home/9720514486/.julia/v0.4/META_BRANCH' exists. `remove_destination=true` is required to remove '/home/9720514486/.julia/v0.4/META_BRANCH' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in init at pkg/dir.jl:64
 in cd at pkg/dir.jl:28
 in status at pkg.jl:32 (repeats 2 times)

**Comment by oyamad** [comment]
とりあえずホームディレクトリ直下の `.julia` ディレクトリを消去してもう一回やってみてください．

@myuuuuun 今度見てあげてください．

**Comment by myuuuuun** [comment]
一旦

```
Pkg.rm("IJulia")
```

して, 再度Pkg.addするのはどうでしょう

**Comment by 13tsuyoshi** [comment]
julia> Pkg.rm("Ijulia")
INFO: Initializing package repository /home/9720514486/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: ArgumentError: '/home/9720514486/.julia/v0.4/REQUIRE' exists. `remove_destination=true` is required to remove '/home/9720514486/.julia/v0.4/REQUIRE' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in init at pkg/dir.jl:63
 in cd at pkg/dir.jl:28
 in rm at pkg.jl:22

**Comment by 13tsuyoshi** [comment]
実行しましたが上のようなエラーが出てなかなかうまくいきません。

**Comment by oyamad** [comment]
`.julia` フォルダを消してやり直してみてください．

**Comment by 13tsuyoshi** [comment]
Pkg.rm("IJulia")
INFO: Initializing package repository /home/9720514486/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: ArgumentError: '/home/9720514486/.julia/v0.4/REQUIRE' exists. `remove_destination=true` is required to remove '/home/9720514486/.julia/v0.4/REQUIRE' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in init at pkg/dir.jl:63
 in cd at pkg/dir.jl:28
 in rm at pkg.jl:22
となっていたので、指示通り、

ターミナルで、ホームデュレクトリ直下にあった.juliaを、　rm -rf .julia　で消して

Pkg.rm("Julia")を行い、Pkg.add("IJulia")したらうまくいきました。
もうijuliaが使える状態になりました。
ありがとうございました。

**Comment by oyamad** [comment]
それならよかったです．
また何かあったら新たな issue を立ててください．
